# Generated by Django 4.2.28 on 2026-02-21 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('metro_city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(default='Canada', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['metro_city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_summary', models.TextField(blank=True, help_text='Short bio about your business, experience, and what you specialize in.', max_length=1000, null=True)),
                ('account_type', models.CharField(choices=[('tradesperson', 'Tradesperson'), ('visitor', 'Visitor')], db_index=True, default='tradesperson', max_length=20)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=10)),
                ('user_firstname', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_preferred_name', models.CharField(max_length=150)),
                ('user_business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_profile_image', models.ImageField(default='no_profile_picture.jpg', upload_to=users.models.profile_image_path)),
                ('user_primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('user_address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('user_city', models.CharField(max_length=100)),
                ('user_province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=50)),
                ('user_postal_code', models.CharField(max_length=10)),
                ('user_website', models.URLField(blank=True, null=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=users.models.work_photo_upload_path, validators=[users.models.validate_gallery_image_size])),
                ('description', models.TextField(blank=True, help_text='Max 100 words.', validators=[users.models.validate_100_words])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(max_length=200)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=users.models.license_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20)),
                ('public_visibility', models.BooleanField(default=True, help_text='Show this license on your public profile')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='users.userprofile')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallOutFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, help_text="E.g. 'Applies to diagnosis/assessment. Waived if job is accepted.'", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callout_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicearea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service_area')},
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.province')),
            ],
            options={
                'unique_together': {('province', 'name')},
            },
        ),
    ]
