# Generated by Django 4.2.28 on 2026-03-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji/icon like 🏆, ⭐, 🔧', max_length=10)),
                ('public_visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
