# Generated by Django 4.2.28 on 2026-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional emoji like 🏆, ⭐, 🔧', max_length=10),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='public_visibility',
            field=models.BooleanField(default=True, help_text='Show this achievement on your public profile'),
        ),
    ]
